services:

  emass:
    profiles: [ all, emass ]
    build: emass
    image: swordfish/emass:latest
    container_name: swordfish-emass
    ports:
      - "4010:4010"
    env_file:
      - .env

  mcp-server:
    profiles: [ all, mcp-server ]
    build: mcp-server
    image: swordfish/mcp-server:latest
    container_name: swordfish-mcp-server
    ports:
      - "8282:8282"
    env_file:
      - .env

  backend:
    profiles: [ all, backend ]
    build: backend
    image: swordfish/backend:latest
    container_name: swordfish-backend
    ports:
      - "8181:8181"
    env_file:
      - .env

  frontend:
    profiles: [ all, frontend ]
    build: frontend
    image: swordfish/frontend:latest
    container_name: swordfish-frontend
    ports:
      - "80:8501"
    env_file:
      - .env
