---
site_name: swordfish
theme:
  name: null
  custom_dir: docs/theme
extra_css:
  - css/theme.css
nav:
  - "Getting Started": user-guide/getting-started.md
  - "Architecture": developer-guide/architecture.md
  - "Data Flow": developer-guide/data-flow.md
  - "Design Principles": developer-guide/design-principles.md
